// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repository/record_pfc_repository.go
//
// Generated by this command:
//
//	mockgen -source=domain/repository/record_pfc_repository.go -destination=mock/mock_record_pfc_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entity "caltrack/domain/entity"
	vo "caltrack/domain/vo"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRecordPfcRepository is a mock of RecordPfcRepository interface.
type MockRecordPfcRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecordPfcRepositoryMockRecorder
	isgomock struct{}
}

// MockRecordPfcRepositoryMockRecorder is the mock recorder for MockRecordPfcRepository.
type MockRecordPfcRepositoryMockRecorder struct {
	mock *MockRecordPfcRepository
}

// NewMockRecordPfcRepository creates a new mock instance.
func NewMockRecordPfcRepository(ctrl *gomock.Controller) *MockRecordPfcRepository {
	mock := &MockRecordPfcRepository{ctrl: ctrl}
	mock.recorder = &MockRecordPfcRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordPfcRepository) EXPECT() *MockRecordPfcRepositoryMockRecorder {
	return m.recorder
}

// FindByRecordID mocks base method.
func (m *MockRecordPfcRepository) FindByRecordID(ctx context.Context, recordID vo.RecordID) (*entity.RecordPfc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRecordID", ctx, recordID)
	ret0, _ := ret[0].(*entity.RecordPfc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRecordID indicates an expected call of FindByRecordID.
func (mr *MockRecordPfcRepositoryMockRecorder) FindByRecordID(ctx, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRecordID", reflect.TypeOf((*MockRecordPfcRepository)(nil).FindByRecordID), ctx, recordID)
}

// FindByRecordIDs mocks base method.
func (m *MockRecordPfcRepository) FindByRecordIDs(ctx context.Context, recordIDs []vo.RecordID) ([]*entity.RecordPfc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRecordIDs", ctx, recordIDs)
	ret0, _ := ret[0].([]*entity.RecordPfc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRecordIDs indicates an expected call of FindByRecordIDs.
func (mr *MockRecordPfcRepositoryMockRecorder) FindByRecordIDs(ctx, recordIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRecordIDs", reflect.TypeOf((*MockRecordPfcRepository)(nil).FindByRecordIDs), ctx, recordIDs)
}

// GetDailyPfc mocks base method.
func (m *MockRecordPfcRepository) GetDailyPfc(ctx context.Context, userID vo.UserID, startTime, endTime time.Time) (vo.DailyPfc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyPfc", ctx, userID, startTime, endTime)
	ret0, _ := ret[0].(vo.DailyPfc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyPfc indicates an expected call of GetDailyPfc.
func (mr *MockRecordPfcRepositoryMockRecorder) GetDailyPfc(ctx, userID, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyPfc", reflect.TypeOf((*MockRecordPfcRepository)(nil).GetDailyPfc), ctx, userID, startTime, endTime)
}

// Save mocks base method.
func (m *MockRecordPfcRepository) Save(ctx context.Context, recordPfc *entity.RecordPfc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, recordPfc)
	ret0, _ := ret[1].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRecordPfcRepositoryMockRecorder) Save(ctx, recordPfc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRecordPfcRepository)(nil).Save), ctx, recordPfc)
}
