// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repository/advice_cache_repository.go
//
// Generated by this command:
//
//	mockgen -source=domain/repository/advice_cache_repository.go -destination=mock/mock_advice_cache_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entity "caltrack/domain/entity"
	vo "caltrack/domain/vo"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAdviceCacheRepository is a mock of AdviceCacheRepository interface.
type MockAdviceCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdviceCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockAdviceCacheRepositoryMockRecorder is the mock recorder for MockAdviceCacheRepository.
type MockAdviceCacheRepositoryMockRecorder struct {
	mock *MockAdviceCacheRepository
}

// NewMockAdviceCacheRepository creates a new mock instance.
func NewMockAdviceCacheRepository(ctrl *gomock.Controller) *MockAdviceCacheRepository {
	mock := &MockAdviceCacheRepository{ctrl: ctrl}
	mock.recorder = &MockAdviceCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdviceCacheRepository) EXPECT() *MockAdviceCacheRepositoryMockRecorder {
	return m.recorder
}

// DeleteByUserIDAndDate mocks base method.
func (m *MockAdviceCacheRepository) DeleteByUserIDAndDate(ctx context.Context, userID vo.UserID, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIDAndDate", ctx, userID, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserIDAndDate indicates an expected call of DeleteByUserIDAndDate.
func (mr *MockAdviceCacheRepositoryMockRecorder) DeleteByUserIDAndDate(ctx, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIDAndDate", reflect.TypeOf((*MockAdviceCacheRepository)(nil).DeleteByUserIDAndDate), ctx, userID, date)
}

// FindByUserIDAndDate mocks base method.
func (m *MockAdviceCacheRepository) FindByUserIDAndDate(ctx context.Context, userID vo.UserID, date time.Time) (*entity.AdviceCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndDate", ctx, userID, date)
	ret0, _ := ret[0].(*entity.AdviceCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndDate indicates an expected call of FindByUserIDAndDate.
func (mr *MockAdviceCacheRepositoryMockRecorder) FindByUserIDAndDate(ctx, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndDate", reflect.TypeOf((*MockAdviceCacheRepository)(nil).FindByUserIDAndDate), ctx, userID, date)
}

// Save mocks base method.
func (m *MockAdviceCacheRepository) Save(ctx context.Context, cache *entity.AdviceCache) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, cache)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAdviceCacheRepositoryMockRecorder) Save(ctx, cache any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAdviceCacheRepository)(nil).Save), ctx, cache)
}
