// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/service/pfc_estimator.go
//
// Generated by this command:
//
//	mockgen -source=usecase/service/pfc_estimator.go -destination=mock/mock_pfc_estimator.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	service "caltrack/usecase/service"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPfcEstimator is a mock of PfcEstimator interface.
type MockPfcEstimator struct {
	ctrl     *gomock.Controller
	recorder *MockPfcEstimatorMockRecorder
	isgomock struct{}
}

// MockPfcEstimatorMockRecorder is the mock recorder for MockPfcEstimator.
type MockPfcEstimatorMockRecorder struct {
	mock *MockPfcEstimator
}

// NewMockPfcEstimator creates a new mock instance.
func NewMockPfcEstimator(ctrl *gomock.Controller) *MockPfcEstimator {
	mock := &MockPfcEstimator{ctrl: ctrl}
	mock.recorder = &MockPfcEstimatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPfcEstimator) EXPECT() *MockPfcEstimatorMockRecorder {
	return m.recorder
}

// Estimate mocks base method.
func (m *MockPfcEstimator) Estimate(ctx context.Context, config service.PfcEstimatorConfig, input service.PfcEstimateInput) (*service.PfcEstimateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Estimate", ctx, config, input)
	ret0, _ := ret[0].(*service.PfcEstimateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Estimate indicates an expected call of Estimate.
func (mr *MockPfcEstimatorMockRecorder) Estimate(ctx, config, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Estimate", reflect.TypeOf((*MockPfcEstimator)(nil).Estimate), ctx, config, input)
}
