// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repository/record_repository.go
//
// Generated by this command:
//
//	mockgen -source=domain/repository/record_repository.go -destination=mock/mock_record_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entity "caltrack/domain/entity"
	repository "caltrack/domain/repository"
	vo "caltrack/domain/vo"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRecordRepository is a mock of RecordRepository interface.
type MockRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockRecordRepositoryMockRecorder is the mock recorder for MockRecordRepository.
type MockRecordRepositoryMockRecorder struct {
	mock *MockRecordRepository
}

// NewMockRecordRepository creates a new mock instance.
func NewMockRecordRepository(ctrl *gomock.Controller) *MockRecordRepository {
	mock := &MockRecordRepository{ctrl: ctrl}
	mock.recorder = &MockRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordRepository) EXPECT() *MockRecordRepositoryMockRecorder {
	return m.recorder
}

// FindByUserIDAndDateRange mocks base method.
func (m *MockRecordRepository) FindByUserIDAndDateRange(ctx context.Context, userID vo.UserID, startTime, endTime time.Time) ([]*entity.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndDateRange", ctx, userID, startTime, endTime)
	ret0, _ := ret[0].([]*entity.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndDateRange indicates an expected call of FindByUserIDAndDateRange.
func (mr *MockRecordRepositoryMockRecorder) FindByUserIDAndDateRange(ctx, userID, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndDateRange", reflect.TypeOf((*MockRecordRepository)(nil).FindByUserIDAndDateRange), ctx, userID, startTime, endTime)
}

// GetDailyCalories mocks base method.
func (m *MockRecordRepository) GetDailyCalories(ctx context.Context, userID vo.UserID, period vo.StatisticsPeriod) ([]repository.DailyCalories, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyCalories", ctx, userID, period)
	ret0, _ := ret[0].([]repository.DailyCalories)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyCalories indicates an expected call of GetDailyCalories.
func (mr *MockRecordRepositoryMockRecorder) GetDailyCalories(ctx, userID, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyCalories", reflect.TypeOf((*MockRecordRepository)(nil).GetDailyCalories), ctx, userID, period)
}

// Save mocks base method.
func (m *MockRecordRepository) Save(ctx context.Context, record *entity.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRecordRepositoryMockRecorder) Save(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRecordRepository)(nil).Save), ctx, record)
}
