// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/service/pfc_analyzer.go
//
// Generated by this command:
//
//	mockgen -source=usecase/service/pfc_analyzer.go -destination=mock/mock_pfc_analyzer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	service "caltrack/usecase/service"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPfcAnalyzer is a mock of PfcAnalyzer interface.
type MockPfcAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockPfcAnalyzerMockRecorder
	isgomock struct{}
}

// MockPfcAnalyzerMockRecorder is the mock recorder for MockPfcAnalyzer.
type MockPfcAnalyzerMockRecorder struct {
	mock *MockPfcAnalyzer
}

// NewMockPfcAnalyzer creates a new mock instance.
func NewMockPfcAnalyzer(ctrl *gomock.Controller) *MockPfcAnalyzer {
	mock := &MockPfcAnalyzer{ctrl: ctrl}
	mock.recorder = &MockPfcAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPfcAnalyzer) EXPECT() *MockPfcAnalyzerMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockPfcAnalyzer) Analyze(ctx context.Context, config service.PfcAnalyzerConfig, input service.NutritionAdviceInput) (*service.NutritionAdviceOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", ctx, config, input)
	ret0, _ := ret[0].(*service.NutritionAdviceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockPfcAnalyzerMockRecorder) Analyze(ctx, config, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockPfcAnalyzer)(nil).Analyze), ctx, config, input)
}
