// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/ai_config.go
//
// Generated by this command:
//
//	mockgen -source=usecase/ai_config.go -destination=mock/mock_ai_config.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAIConfig is a mock of AIConfig interface.
type MockAIConfig struct {
	ctrl     *gomock.Controller
	recorder *MockAIConfigMockRecorder
	isgomock struct{}
}

// MockAIConfigMockRecorder is the mock recorder for MockAIConfig.
type MockAIConfigMockRecorder struct {
	mock *MockAIConfig
}

// NewMockAIConfig creates a new mock instance.
func NewMockAIConfig(ctrl *gomock.Controller) *MockAIConfig {
	mock := &MockAIConfig{ctrl: ctrl}
	mock.recorder = &MockAIConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIConfig) EXPECT() *MockAIConfigMockRecorder {
	return m.recorder
}

// GeminiModelName mocks base method.
func (m *MockAIConfig) GeminiModelName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeminiModelName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GeminiModelName indicates an expected call of GeminiModelName.
func (mr *MockAIConfigMockRecorder) GeminiModelName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeminiModelName", reflect.TypeOf((*MockAIConfig)(nil).GeminiModelName))
}
