// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/service/image_analyzer.go
//
// Generated by this command:
//
//	mockgen -source=usecase/service/image_analyzer.go -destination=mock/mock_image_analyzer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	service "caltrack/usecase/service"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImageAnalyzer is a mock of ImageAnalyzer interface.
type MockImageAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockImageAnalyzerMockRecorder
	isgomock struct{}
}

// MockImageAnalyzerMockRecorder is the mock recorder for MockImageAnalyzer.
type MockImageAnalyzerMockRecorder struct {
	mock *MockImageAnalyzer
}

// NewMockImageAnalyzer creates a new mock instance.
func NewMockImageAnalyzer(ctrl *gomock.Controller) *MockImageAnalyzer {
	mock := &MockImageAnalyzer{ctrl: ctrl}
	mock.recorder = &MockImageAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageAnalyzer) EXPECT() *MockImageAnalyzerMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockImageAnalyzer) Analyze(ctx context.Context, config service.ImageAnalyzerConfig, imageData, mimeType string) ([]service.AnalyzedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", ctx, config, imageData, mimeType)
	ret0, _ := ret[0].([]service.AnalyzedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockImageAnalyzerMockRecorder) Analyze(ctx, config, imageData, mimeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockImageAnalyzer)(nil).Analyze), ctx, config, imageData, mimeType)
}
